### ISSUE TITLE
erro ao rodar 

### ISSUE THREAD

**Issue by CarlosAugustoP** [gabrielpires-1/vitali-tech#3]
ao rodar o codigo com gcc, deparamo-nos com o erro:  

main.c: In function 'main':
main.c:226:31: warning: comparison between pointer and integer
           if(confirm_feedback == 's' || confirm_feedback == 'S')
                               ^~
main.c:226:58: warning: comparison between pointer and integer
           if(confirm_feedback == 's' || confirm_feedback == 'S')
                                                          ^~
main.c:241:38: warning: comparison between pointer and integer
           }else if (confirm_feedback == 'n' || confirm_feedback == 'N'){
                                      ^~
main.c:241:65: warning: comparison between pointer and integer
           }else if (confirm_feedback == 'n' || confirm_feedback == 'N'){
                                                                 ^~
lib.c: In function 'create_feedback':
lib.c:542:12: warning: passing argument 1 of 'strcpy' makes pointer from integer without a cast [-Wint-conversion]
     strcpy(new_feedback->tags[i], tag_list[i]);
            ^~~~~~~~~~~~
In file included from lib.c:4:0:
c:\mingw\include\string.h:79:40: note: expected 'char *' but argument is of type 'char'
 _CRTIMP __cdecl __MINGW_NOTHROW  char *strcpy (char *, const char *);

**Comment by dan-albuquerque** [comment]
Resolvido, quando tive que resolver um problema do git pull, esqueci de alterar um atributo da struct de feedbacks e de mudar a variável "confirm_feedback" de string para caracter
