### ISSUE TITLE
Inputs errados na seleção de tags para feedback

### ISSUE THREAD

**Issue by mihevi** [gabrielpires-1/vitali-tech#4]
ao selecionar a opção de 4 tags, recebemos uma mensagem de erro dizendo que o limite é 4.
![imagem_2023-06-12_180150726](https://github.com/gabrielpires-1/vitali-tech/assets/94465844/958b9f4f-01fd-49ac-9fbc-9bf51302a759)
ao usar uma tag diferente de 0 a 3 recebemos o seguinte erro (inputs selecionados: 4 , 0 , 1)
![imagem_2023-06-12_180621956](https://github.com/gabrielpires-1/vitali-tech/assets/94465844/10443e75-1775-4bce-891d-dd9fa1850973)
no arquivo feedback.txt fica salvo como 0 , 1 , 2
![imagem_2023-06-12_180714440](https://github.com/gabrielpires-1/vitali-tech/assets/94465844/b4c1eacf-5904-46eb-80e9-0a0fd56a133a)
em outro caso, quando digitado 2 (atencioso) e 4 (;ztÄö⌂), feedback.txt ficou salvo como 0 (comunicativo) e 1 (dedicado)

**Comment by dan-albuquerque** [comment]
Alterei o if que antes estava >= 4 para > 4 resolvendo a questão de inconsistência de "você só pode inserir ate 4 tags!" e coloquei uma checagem em um while e caso o usuário insira um valor invalido ele reseta a contagem.
